Repository ublue-os/ucore, pull requests merged in 2024-07, with the labels that each got.

#169 refactor: update cosign public key
  cosign.pub
Labels: size:XS, lgtm

#170 refactor: use akmods repo as source for kmods
  .github/workflows/reusable-build.yml
  README.md
  fedora-coreos/Containerfile
  fedora-coreos/install.sh
  ucore/Containerfile
  ucore/install-ucore-minimal.sh
Labels: enhancement, size:L, lgtm

#172 feat: add package intel-compute-runtime to ucore
  ucore/packages.json
Labels: enhancement, size:XS, lgtm

#177 feat: use ublue-os-signing RPM from config
  .github/workflows/reusable-build.yml
  fedora-coreos/Containerfile
  ucore/Containerfile
  ucore/usr/etc/containers/policy.json
  ucore/usr/etc/containers/registries.d/ublue-os.yaml
  ucore/usr/etc/pki/containers/ublue-os.pub
Labels: enhancement, size:L, lgtm

#178 fix: do not install pre-release packages
  ucore/install-ucore-hci.sh
  ucore/install-ucore-minimal.sh
Labels: bug, size:S, lgtm

#179 chore(ci): reduce copy layers
  .github/workflows/reusable-build.yml
  fedora-coreos/Containerfile
  fedora-coreos/cleanup.sh
  fedora-coreos/install.sh
  ucore/Containerfile
  ucore/cleanup.sh
  ucore/install-ucore-hci.sh
  ucore/install-ucore-minimal.sh
  ucore/install-ucore.sh
  ucore/packages.sh
  ucore/post-install-ucore-minimal.sh
Labels: size:L, lgtm
