Repository ublue-os/ucore, pull requests merged in 2024-11, with the labels that each got.

#208 chore: temporarily pause stable scheduled builds
  .github/workflows/build-stable.yml
  .github/workflows/build-testing.yml
Labels: size:S, lgtm

#209 chore(ci): Use kernel-cache for kernel-version
  .github/workflows/build-stable.yml
  .github/workflows/reusable-build.yml
  README.md
Labels: size:M, lgtm

#211 fix: possible fix for apparent ZFS depmod fail
  fedora-coreos/install.sh
  ucore/install-ucore-minimal.sh
Labels: zfs, size:XS, lgtm

#213 fix: restore mergerfs in f41
  ucore/install-ucore.sh
Labels: documentation, size:S, lgtm

#146 feat: add zfs-scrub systemd units
  README.md
  ucore/usr/lib/systemd/system/zfs-scrub-monthly@.timer
  ucore/usr/lib/systemd/system/zfs-scrub-weekly@.timer
  ucore/usr/lib/systemd/system/zfs-scrub@.service
Labels: size:M, lgtm

#215 fix: github release install silently fails if no urls found
  ucore/github-release-install.sh
Labels: bug, size:S, lgtm

#218 docs: create parent dirs in README.md
  README.md
Labels: documentation, size:XS, lgtm

#216 docs: fix typo in README
  README.md
Labels: documentation, size:XS, lgtm

#219 chore(ci): don't run ci for markdown changes
  .github/workflows/build-stable.yml
  .github/workflows/build-testing.yml
Labels: size:XS, lgtm

#220 fix: restore mergerfs RPM install
  ucore/install-ucore.sh
Labels: bug, size:S, lgtm
