Repository ublue-os/ucore, pull requests merged in 2024-09, with the labels that each got.

#197 chore(ci): don't block non-zfs/non-nivdia testing builds
  .github/workflows/reusable-build.yml
Labels: size:S, lgtm

#186 feat: Add zfs-dracut to fedora-coreos and ucore
  fedora-coreos/install.sh
  ucore/install-ucore-minimal.sh
Labels: zfs, size:XS, lgtm

#198 chore(ci): update cron schedule to follow akmods
  .github/workflows/build-stable.yml
  .github/workflows/build-testing.yml
Labels: size:XS, lgtm

#201 docs: - Fixed 'minimal' typo in README
  README.md
Labels: documentation, size:XS, lgtm

#200 docs: add podman auto-start info and cleanup structure
  README.md
Labels: documentation, size:M, lgtm
