Repository ublue-os/ucore, pull requests merged in 2025-05, with the labels that each got.

#252 docs: notice of transition period F42
  README.md
Labels: documentation, size:XS, lgtm

#253 refactor: update to dnf5, use ublue packages
  .github/workflows/reusable-build.yml
  fedora-coreos/Containerfile
  fedora-coreos/cleanup.sh
  fedora-coreos/install.sh
  ucore/Containerfile
  ucore/cleanup.sh
  ucore/github-release-install.sh
  ucore/install-ucore-minimal.sh
  ucore/install-ucore.sh
  ucore/packages.json
  ucore/packages.sh
  ucore/post-install-ucore-minimal.sh
  ucore/system_files/usr/lib/systemd/system/libvirt-workaround.service
  ucore/system_files/usr/lib/tmpfiles.d/libvirt-workaround.conf
Labels: enhancement, size:L, lgtm

#255 fix: remove excluded packages and announce Fedora 42 for uCore
  README.md
  ucore/github-release-install.sh
  ucore/install-ucore-minimal.sh
  ucore/install-ucore.sh
  ucore/packages.sh
Labels: documentation, size:M, lgtm

#262 feat: Update install-ucore.sh to include variant_id for countme
  ucore/install-ucore-minimal.sh
Labels: size:XS, lgtm

#264 chore: update docker buildx/compose plugins
  ucore/Containerfile
Labels: dependencies, size:XS, lgtm

#260 fix: System files copy of `/etc` dir
  ucore/Containerfile
Labels: bug, size:XS, lgtm
