Repository ublue-os/ucore, pull requests merged in 2025-01, with the labels that each got.

#226 fix: correct the filename for ConditionPathExists on ucore-signed-autorebase.service
  examples/ucore-autorebase.butane
Labels: bug, size:XS, lgtm

#145 feat: add cockpit-zfs-manager for zfs builds
  README.md
  ucore/install-ucore.sh
Labels: size:S, lgtm

#231 docs: Add install example and fix fcontext commands
  README.md
Labels: documentation, size:S, lgtm
