Repository ublue-os/ucore, pull requests merged in 2025-06, with the labels that each got.

#266 feat: streamline builds, drop fedora-coreos, include ZFS in all
  .github/workflows/reusable-build.yml
  README.md
  fedora-coreos/Containerfile
  fedora-coreos/cleanup.sh
  fedora-coreos/install.sh
  fedora-coreos/post-install.sh
  ucore/Containerfile
  ucore/install-ucore-minimal.sh
  ucore/install-ucore.sh
  ucore/packages.json
  ucore/post-install-ucore-minimal.sh
Labels: zfs, size:XL, lgtm

#267 fix: Put policy.json in correct spot and cleanup /usr/etc for bootc container lint
  ucore/Containerfile
  ucore/install-ucore-minimal.sh
Labels: size:S, lgtm

#269 chore: remove unused/redundant zfs scrub services/timers
  ucore/usr/lib/systemd/system/zfs-scrub-monthly@.timer
  ucore/usr/lib/systemd/system/zfs-scrub-weekly@.timer
  ucore/usr/lib/systemd/system/zfs-scrub@.service
Labels: zfs, size:M, lgtm
